### ISSUE TITLE
local storage missing in  docker-compose

### ISSUE THREAD

**Issue by ippocratis** [tagspaces/tagspaces#1843]
**Describe the bug**
Run with docker-compose
Local storage is missing
only object storage is available
And I cant see any docker related documentation

**Comment by sytolk** [comment]
@ippocratis yes documentation is missing yet and docker-compose install in docker container web version of the tagspaces - you can't access local filesystem from web browser this is the reason that only object storage is available. 
But if you check in [docker-compose.yml](https://github.com/tagspaces/tagspaces/blob/develop/docker/docker-compose.yml) file there is minio container too and you can create new Object Store location that will access local file system.
TODO if you like to make Pull Request you can save minio object storage location in tagspaces [extconfig](https://docs.tagspaces.org/dev/external-config/#configuring-custom-locations) and next time you run from `/docker` folder `docker-compose up` you will have in web browser Tagspaces with predefined Object Storage location.

**Comment by ippocratis** [comment]
MinIO container is exiting on raspberryPi400
`tagspaces-minio-1 exited with code 0`

**Comment by ippocratis** [comment]
Changed the compose a bit
this one seems to work

```
version: '3.9'
networks:
  app-ts:
    driver: bridge
services:
  tagspaces-web:
    build: .
    ports:
      - '8399:80'
    volumes:
      - ./www:/usr/share/nginx/www/
    networks:
      - app-ts
  minio:
    image: 'minio/minio'
    ports:
      - '9088:9000'
      - '9089:9001'
    volumes:
      - './minio_storage:/data'
    environment:
      - MINIO_ROOT_USER=miniusername
      - MINIO_ROOT_PASSWORD=miniopassword
    command: server --console-address ":9001" /data
    networks:
      - app-ts
```
